### ISSUE TITLE
Source code for reveal js and Sozi slides?

### ISSUE THREAD

**Issue by kdmarrett** [davidthings/spokefpga#3]
The slides for Hackaday on FPGA are remarkable: https://davidthings.github.io/spokefpga/hackaday_slides_2019_11_12/#/

But I can't find source folder for how you generated them. I found the html output of your reveal js ai_slides in another repo, but there's no source from where you generated it for others to fork and have similarly clear presentations. In particular, it's not clear how one can embed or combine a Sozi slide into a reveal js presentation anywhere else on the internet, which would be very useful in my own slides for FPGA/embedded work for advanced zooming into large microarchitecture diagrams.

I appreciate the help and would love to pass on someone of your presentation hacks to the rest of my lab!

**Comment by davidthings** [comment]
Hi!  Sorry for the slow reply... notifications are not finding me at the moment for some reason.

As far as the inserting Sozi slides into Reveal Js presentations issue is concerned, it was a while ago and memory doesn't serve super well, but to 90% certainty, the slides were all written in reveal html markup in a text editor and so the sozi-generated frames were likely just dumped in...

For example, the following looks like iframe boilerplate with a reference to the right file.

```
<section data-background-iframe="sozi/fpga_physical.sozi.html" data-background-interactive>
    <div style="position: absolute; width: 1%; right: 0; box-shadow: 0 1px 4px rgba(0,0,0,0.5), 0 5px 25px rgba(0,0,0,0.2); background-color: rgba(60, 60, 60, 0.9); color: #fff; padding: 20px; font-size: 20px; text-align: right;">
    </div>
</section>
```
And thanks for the nice words about the slides!

**Comment by kdmarrett** [comment]
Ah that makes sense, thank you!
